name: build
on: [push]
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - uses: gradle/gradle-build-action@v3
        with: { arguments: :app:assembleDebug }
      - uses: actions/upload-artifact@v4
        with:
          name: JarvisMicBridge-debug
          path: app/build/outputs/apk/debug/app-debug.apk
