name: Android Build
on:
  push: { branches: [ master ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: android-actions/setup-android@v3
      - name: Accept licenses + install SDK
        run: |
          yes | sdkmanager --licenses >/dev/null
          yes | sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
      - name: Build with Gradle 8.7 (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: :app:assembleDebug --stacktrace --warning-mode=all
      - uses: actions/upload-artifact@v4
        with:
          name: JarvisMicBridge-debug
          path: app/build/outputs/apk/debug/app-debug.apk
